#!/usr/bin/env sh
./src/app.js -h
./src/app.js -s hatlesshacker/example-gitsie-repo
./src/app.js -l hatlesshacker/example-gitsie-repo
./src/app.js -r hatlesshacker/example-gitsie-repo
./src/app.js -i hatlesshacker/example-gitsie-repo $HOME
./src/app.js -d hatlesshacker/example-gitsie-repo
